plugins:
  discord_bot_enabled:
    default: true
    client: false
  discord_bot_token:
    default: ''
    client: false
  discord_bot_admin_channel_id:
    default: ''
    client: false
  discord_bot_admin_role_id:
    default: ''
    client: false
  discord_bot_post_announcement_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  discord_bot_topic_announcement_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  discord_bot_rate_limit_delay:
    default: 2
    client: false
